version: "3"

services:

  netcore:
    container_name: dev-netcore
    image: mcr.microsoft.com/dotnet/sdk:3.1
    restart: always
    volumes:
      - ./../src:/app
      # - ./../src/bin/Release/netcoreapp3.1/publish:/app
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - mariadb
    working_dir: /app
    command: dotnet watch run --urls="http://+:5000;https://+:5001"
    # command: ./app --urls="http://+:5000;https://+:5001"

  mariadb:
    container_name: dev-mariadb
    restart: always
    image: mariadb:10.5.8
    volumes:
      - ./../sql:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root